# Generated by Django 4.2.13 on 2024-06-23 16:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilename', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_profilename', message='Profile name can only contain alphanumeric characters and underscores', regex='^[a-zA-Z0-9_]+$')], verbose_name='Profile handle')),
                ('display_name', models.CharField(default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='', verbose_name='About')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='Lives in')),
                ('occupation', models.CharField(blank=True, default='', max_length=255, verbose_name='Works as')),
                ('tags', models.CharField(blank=True, default='', help_text='Enter interests as a comma-separated list (e.g., Camping, Technology, History).', max_length=255, verbose_name='Interests')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
                ('profile_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofiles.userprofile')),
            ],
        ),
    ]
