# Generated by Django 4.2.13 on 2024-05-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_alter_userprofile_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='skills',
            new_name='tags',
        ),
    ]
