# Generated by Django 4.2.13 on 2024-05-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_rename_skills_userprofile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Wroks as'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Workplace'),
        ),
    ]
