# Generated by Django 4.2.13 on 2024-05-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0006_alter_userprofile_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='text', max_length=255),
        ),
    ]
