# Generated by Django 4.2.13 on 2024-05-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_alter_userprofile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Enter tags as a comma-separated list (e.g., tag1, tag2, tag3).', max_length=255),
        ),
    ]
