# Generated by Django 4.2.13 on 2024-06-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0008_alter_userprofile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Enter interests as a comma-separated list (e.g., Camping, Technology, History).', max_length=255, verbose_name='Interests'),
        ),
    ]
