# Generated by Django 4.2.13 on 2024-06-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0009_alter_userprofile_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_links',
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='userprofiles.userprofile'),
        ),
    ]
