# Generated by Django 4.2.13 on 2024-06-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0010_remove_userprofile_social_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofiles.userprofile'),
        ),
    ]
