# Generated by Django 4.2.13 on 2024-06-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0012_remove_userprofile_city_remove_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='About'),
        ),
    ]
