services:
  docs:
    image: linkpage_local_docs
    container_name: linkpage_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./linkpage:/app/linkpage:z
    ports:
      - '9000:9000'
    command: /start-docs
